--- 
abstract: Extensible and flexible object <-> relational mapper.
author: "mst: Matt S. Trout <mst@shadowcatsystems.co.uk>"
build_requires: 
  DBD::SQLite: 1.11
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
  Class::Accessor::Grouped: 0.05002
  Class::C3: 0.13
  Class::Inspector: 0
  Cwd: 3.19
  DBI: 1.4
  Data::Page: 2
  JSON: 1
  Module::Find: 0
  SQL::Abstract: 1.2
  SQL::Abstract::Limit: 0.101
  Scalar::Util: 0
  Storable: 0
  perl: 5.6.1
tests: t/*.t t/*/*.t
version: 0.07999_04
