---
abstract: 'Extensible and flexible object <-> relational mapper.'
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  DBD::SQLite: 1.25
  File::Temp: 0.22
  Test::Builder: 0.33
  Test::Exception: 0
  Test::More: 0.92
  Test::Warn: 0.21
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class
no_index:
  directory:
    - examples
    - inc
    - lib/DBIx/Class/Admin
    - lib/DBIx/Class/CDBICompat
    - lib/DBIx/Class/PK/Auto
    - lib/DBIx/Class/SQLAHacks
    - t
    - xt
  package:
    - DBIx::Class::SQLAHacks
    - DBIx::Class::Storage::DBIHacks
requires:
  Carp::Clan: 6.0
  Class::Accessor::Grouped: 0.09003
  Class::C3::Componentised: 1.0005
  Class::DBI::Plugin::DeepAbstractSearch: 0
  Class::Inspector: 1.24
  Class::Trigger: 0
  Clone: 0
  Context::Preserve: 0.01
  DBD::SQLite: 1.25
  DBI: 1.609
  DBIx::ContextualFetch: 0
  Data::Dumper::Concise: 1.000
  Data::Page: 2.00
  Date::Simple: 3.03
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  DateTime::Format::SQLite: 0
  DateTime::Format::Strptime: 0
  Devel::Cycle: 1.10
  File::Temp: 0.22
  Getopt::Long::Descriptive: 0.081
  Hash::Merge: 0.12
  JSON::Any: 1.22
  MRO::Compat: 0.09
  Module::Find: 0.06
  Moose: 0.98
  MooseX::Types: 0.21
  MooseX::Types::JSON: 0.02
  MooseX::Types::Path::Class: 0.05
  Path::Class: 0.18
  Pod::Coverage: 0.20
  SQL::Abstract: 1.67
  SQL::Abstract::Limit: 0.13
  SQL::Translator: 0.11006
  Scope::Guard: 0.03
  Sub::Name: 0.04
  Test::Builder: 0.33
  Test::EOL: 0.6
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::More: 0.92
  Test::NoTabs: 0.9
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  Test::Warn: 0.21
  Text::CSV: 1.16
  Time::Piece::MySQL: 0
  Try::Tiny: 0.04
  namespace::autoclean: 0.09
  namespace::clean: 0.14
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  homepage: http://www.dbix-class.org/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class.git
version: 0.08122
