--- #YAML:1.0
name: DBIx-Class
version: 0.05003
author:
  - Matt S. Trout <mst@shadowcatsystems.co.uk>
abstract: Extensible and flexible object <-> relational mapper.
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
