---
abstract: 'Extensible and flexible object <-> relational mapper.'
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  Test::Builder: 0.33
  Test::Deep: 0
  Test::Exception: 0
  Test::Warn: 0.11
configure_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  SQL::Translator: 0.09004
requires:
  Carp::Clan: 0
  Class::Accessor::Grouped: 0.08003
  Class::C3::Componentised: 1.0005
  Class::Inspector: 0
  DBD::SQLite: 1.23
  DBI: 1.4
  Data::Page: 2
  JSON::Any: 1.17
  List::Util: 1.19
  MRO::Compat: 0.09
  Module::Find: 0
  Path::Class: 0
  SQL::Abstract: 1.51
  SQL::Abstract::Limit: 0.13
  Scalar::Util: 0
  Scope::Guard: 0.03
  Storable: 0
  Sub::Name: 0.04
  perl: 5.6.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/svnweb/bast/browse/DBIx-Class/
version: 0.08102
