---
abstract: 'Extensible and flexible object <-> relational mapper.'
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  DBD::SQLite: 1.29
  File::Temp: 0.22
  Package::Stash: 0.28
  Test::Builder: 0.33
  Test::Exception: 0.31
  Test::More: 0.92
  Test::Warn: 0.21
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class
no_index:
  directory:
    - examples
    - inc
    - lib/DBIx/Class/Admin
    - lib/DBIx/Class/CDBICompat
    - lib/DBIx/Class/PK/Auto
    - t
    - xt
  package:
    - DBIx::Class::Storage::DBIHacks
    - DBIx::Class::Carp
requires:
  Class::Accessor::Grouped: 0.10002
  Class::C3::Componentised: 1.0009
  Class::Inspector: 1.24
  Config::Any: 0.20
  Context::Preserve: 0.01
  DBI: 1.57
  Data::Compare: 1.22
  Data::Dumper::Concise: 2.020
  Data::Page: 2.00
  File::Path: 2.07
  Hash::Merge: 0.12
  MRO::Compat: 0.09
  Module::Find: 0.06
  Path::Class: 0.18
  SQL::Abstract: 1.72
  Scope::Guard: 0.03
  Sub::Name: 0.04
  Try::Tiny: 0.04
  Variable::Magic: 0.44
  namespace::clean: 0.20
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class
  homepage: http://www.dbix-class.org/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class.git
version: 0.08194
