--- #YAML:1.0
name: DBIx-Class
version: 0.04999_01
author:
  - Matt S. Trout <mst@shadowcatsystems.co.uk>
abstract: Extensible and flexible object <-> relational mapper.
license: perl
generated_by: Module::Build version 0.2603, without YAML.pm
