---
name: DBIx-Class
version: 0.06001
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
abstract: Extensible and flexible object <-> relational mapper.
license: perl
requires:
  Carp::Clan: 0
  Class::C3: 0.11
  Class::Data::Accessor: 0.01
  DBI: 1.4
  Data::Page: 2
  SQL::Abstract: 1.2
  SQL::Abstract::Limit: 0.101
  Scalar::Util: 0
  Storable: 0
recommends:
  Class::Inspector: 0
  Data::UUID: 0
  Module::Find: 0
build_requires:
  DBD::SQLite: 1.11
provides:
  DBIC::SQL::Abstract:
    file: lib/DBIx/Class/Storage/DBI.pm
  DBIx::Class:
    file: lib/DBIx/Class.pm
    version: 0.06001
  DBIx::Class::AccessorGroup:
    file: lib/DBIx/Class/AccessorGroup.pm
  DBIx::Class::CDBICompat:
    file: lib/DBIx/Class/CDBICompat.pm
  DBIx::Class::CDBICompat::ColumnGroups::GrouperShim:
    file: lib/DBIx/Class/CDBICompat/ColumnGroups.pm
  DBIx::Class::Core:
    file: lib/DBIx/Class/Core.pm
  DBIx::Class::Cursor:
    file: lib/DBIx/Class/Cursor.pm
  DBIx::Class::DB:
    file: lib/DBIx/Class/DB.pm
  DBIx::Class::InflateColumn:
    file: lib/DBIx/Class/InflateColumn.pm
  DBIx::Class::PK:
    file: lib/DBIx/Class/PK.pm
  DBIx::Class::PK::Auto:
    file: lib/DBIx/Class/PK/Auto.pm
  DBIx::Class::PK::Auto::DB2:
    file: lib/DBIx/Class/PK/Auto/DB2.pm
  DBIx::Class::PK::Auto::MSSQL:
    file: lib/DBIx/Class/PK/Auto/MSSQL.pm
  DBIx::Class::PK::Auto::MySQL:
    file: lib/DBIx/Class/PK/Auto/MySQL.pm
  DBIx::Class::PK::Auto::Oracle:
    file: lib/DBIx/Class/PK/Auto/Oracle.pm
  DBIx::Class::PK::Auto::Pg:
    file: lib/DBIx/Class/PK/Auto/Pg.pm
  DBIx::Class::PK::Auto::SQLite:
    file: lib/DBIx/Class/PK/Auto/SQLite.pm
  DBIx::Class::Relationship:
    file: lib/DBIx/Class/Relationship.pm
  DBIx::Class::Relationship::Base:
    file: lib/DBIx/Class/Relationship/Base.pm
  DBIx::Class::Relationship::BelongsTo:
    file: lib/DBIx/Class/Relationship/BelongsTo.pm
  DBIx::Class::ResultSet:
    file: lib/DBIx/Class/ResultSet.pm
  DBIx::Class::ResultSetManager:
    file: lib/DBIx/Class/ResultSetManager.pm
  DBIx::Class::ResultSource:
    file: lib/DBIx/Class/ResultSource.pm
  DBIx::Class::ResultSource::Table:
    file: lib/DBIx/Class/ResultSource/Table.pm
  DBIx::Class::ResultSourceProxy::Table:
    file: lib/DBIx/Class/ResultSourceProxy/Table.pm
  DBIx::Class::Row:
    file: lib/DBIx/Class/Row.pm
  DBIx::Class::Schema:
    file: lib/DBIx/Class/Schema.pm
  DBIx::Class::Serialize::Storable:
    file: lib/DBIx/Class/Serialize/Storable.pm
  DBIx::Class::Storage::DBI:
    file: lib/DBIx/Class/Storage/DBI.pm
  DBIx::Class::Storage::DBI::Cursor:
    file: lib/DBIx/Class/Storage/DBI/Cursor.pm
  DBIx::Class::Storage::DBI::DB2:
    file: lib/DBIx/Class/Storage/DBI/DB2.pm
  DBIx::Class::Storage::DBI::DebugCallback:
    file: lib/DBIx/Class/Storage/DBI.pm
  DBIx::Class::Storage::DBI::MSSQL:
    file: lib/DBIx/Class/Storage/DBI/MSSQL.pm
  DBIx::Class::Storage::DBI::MultiDistinctEmulation:
    file: lib/DBIx/Class/Storage/DBI/MultiDistinctEmulation.pm
  DBIx::Class::Storage::DBI::Oracle:
    file: lib/DBIx/Class/Storage/DBI/Oracle.pm
  DBIx::Class::Storage::DBI::Pg:
    file: lib/DBIx/Class/Storage/DBI/Pg.pm
  DBIx::Class::Storage::DBI::SQLite:
    file: lib/DBIx/Class/Storage/DBI/SQLite.pm
  DBIx::Class::Storage::DBI::mysql:
    file: lib/DBIx/Class/Storage/DBI/mysql.pm
  DBIx::Class::Storage::NESTED_ROLLBACK_EXCEPTION:
    file: lib/DBIx/Class/Storage.pm
  DBIx::Class::Test::SQLite:
    file: lib/DBIx/Class/Test/SQLite.pm
  DBIx::Class::UTF8Columns:
    file: lib/DBIx/Class/UTF8Columns.pm
  DBIx::Class::UUIDColumns:
    file: lib/DBIx/Class/UUIDColumns.pm
  DBIx::Class::UUIDMaker:
    file: lib/DBIx/Class/UUIDMaker.pm
  DBIx::Class::UUIDMaker::APR::UUID:
    file: lib/DBIx/Class/UUIDMaker/APR/UUID.pm
  DBIx::Class::UUIDMaker::Data::UUID:
    file: lib/DBIx/Class/UUIDMaker/Data/UUID.pm
  DBIx::Class::UUIDMaker::Data::Uniqid:
    file: lib/DBIx/Class/UUIDMaker/Data/Uniqid.pm
  DBIx::Class::UUIDMaker::UUID:
    file: lib/DBIx/Class/UUIDMaker/UUID.pm
  DBIx::Class::UUIDMaker::Win32::Guidgen:
    file: lib/DBIx/Class/UUIDMaker/Win32/Guidgen.pm
  DBIx::Class::UUIDMaker::Win32API::GUID:
    file: lib/DBIx/Class/UUIDMaker/Win32API/GUID.pm
  DBIx::Class::Validation:
    file: lib/DBIx/Class/Validation.pm
    version: 0.01
  DBIx::ContextualFetch::st:
    file: lib/DBIx/Class/CDBICompat/ImaDBI.pm
  SQL::Translator::Producer::DBIx::Class::File:
    file: lib/SQL/Translator/Producer/DBIx/Class/File.pm
    version: 0.1
generated_by: Module::Build version 0.2611
