---
abstract: 'Extensible and flexible object <-> relational mapper.'
author:
  - 'mst: Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  Class::Trigger: 0
  DBD::SQLite: 1.14
  DBIx::ContextualFetch: 0
  Test::Builder: 0.33
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Accessor::Grouped: 0.08002
  Class::C3: 0.2
  Class::C3::Componentised: 0
  Class::Inspector: 0
  DBI: 1.4
  Data::Page: 2
  JSON::Any: 1.17
  Module::Find: 0
  SQL::Abstract: 1.24
  SQL::Abstract::Limit: 0.13
  Scalar::Util: 0
  Scope::Guard: 0.03
  Storable: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.08011
